

name: Update README

on:
  push:
    paths:
      - 'README.md'
  pull_request:
    paths:
      - 'README.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Update README
        run: |
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.event.repository.name }}
          sed -i "s/OWNER/${REPO_OWNER}/g" README.md
          sed -i "s/REPOSITORY/${REPO_NAME}/g" README.md
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Update README with correct repo info"
          git push origin main
